version: '3'

services:
    app:
        container_name: garden_server
        build:
            dockerfile: ./Dockerfile
        ports:
            # - 8000:8000
            - 80:8000
        build:
            context: .
        restart: on-failure
        volumes:
            - ./:/app/
            - /etc/localtime:/etc/localtime:ro
        environment:
            - TZ=Asia/Seoul
        depends_on:
            - mongo
        command:
            - bash
            - -c
            - |
                echo yes | python manage.py collectstatic
                gunicorn garden5.wsgi:application --bind=0.0.0.0:8000
        networks:
            - garden5

    mongo:
        image: mongo:latest
        container_name: container_mongo
        volumes: 
            - ./:/app/config
            - /etc/localtime:/etc/localtime:ro
        environment: 
            - TZ=Asia/Seoul
        networks:
            - garden5
        expose: 
            - 27017
        ports:
            - 127.0.0.1:27016:27017
        # command:
            # - mongo
            # - use garden5
            # - db.createCollection("slack_messages")
            # - db.slack_messages.createIndex({ts:1}, {unique:true})

            # - |
            #     use garden5
            #     db.createCollection("slack_messages")
            #     db.slack_messages.createIndex({ts:1}, {unique: true})

networks:
    garden5:
        driver: bridge
